#! /bin/bash

workload=${1-tpcc1000}
s3_args="access-key=YOURACCESSKEY&secret-access-key=YOURSECRETKEY&endpoint=http://172.16.4.4:30812"
storage=${storage-"s3://mybucket/ycsb?$s3_args"}

log "starting restore."

/br/bin/br restore full \
    --log-file ${ARTIFICATS-.}/br-restore-full.log \
    --log-level DEBUG \
    --pd $PD_ADDR \
    -s storage

log "restore done; starting backup"

/br/bin/br backup full \
    --log-file ${ARTIFICATS-.}/br-backup-full.log \
    --log-level DEBUG \
    --pd $PD_ADDR \
    -s "local:///tmp/backup"
    # it would be OK to backup to local if the workload is small.
    # TODO backup to s3 bucket.

log "start backup"